/*Create a "Products" table and write two queries, one for finding 
the cheapest product and one to find the costliest product.*/

CREATE TABLE IF NOT EXISTS PRODUCT(
PRODUCTID TEXT PRIMARY KEY,
NAME TEXT,
PRICE INTEGER,
QUANTITY INTEGER
);
INSERT INTO PRODUCT(PRODUCTID,NAME,PRICE,QUANTITY) VALUES
('P1','LAYS',100,3),
('P2','THINKPAD',400000,1),
('P3','CONSOLES',300000,2),
('P4','TISSUE',500,1),
('P5','CHAIR',50000,1);
SELECT * FROM PRODUCT WHERE PRICE=(SELECT MIN(PRICE) FROM PRODUCT);
SELECT * FROM PRODUCT WHERE PRICE=(SELECT MAX(PRICE) FROM PRODUCT);
SELECT * FROM PRODUCT WHERE NAME LIKE 'C%'; 
SELECT  * FROM PRODUCT WHERE NAME LIKE '_A%';
SELECT * FROM PRODUCT WHERE NAME LIKE 'C%S';